server.port: 8091
spring.datasource:
  url: jdbc:postgresql://postgres:5432/postgres
#  url: jdbc:postgresql://postgres:45534/postgres
  username: postgres_user
  password: postgres_password
  driver-class-name: org.postgresql.Driver

#spring:
#  liquibase:
#    change-log: classpath:sql/changeLog-master.yml
#spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL10Dialect
